### ISSUE TITLE
Error Running: docker-compose up

### ISSUE THREAD

**Issue by jersonjunior** [joshuar/elk-ping#1]
ERROR: create kibana/config: volume name invalid: "kibana/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

**Comment by ghost** [comment]
Am getting the same issue. This is the first I am using Docker so I am suspecting that it's to do with that. @jersonjunior any pointer how you fixed the issue? Am assuming that you fixed it since you closed your own issue.
